<a href="https://colab.research.google.com/github/krutuja9/Complete_Python/blob/master/AgricultureData.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
df = pd.read_csv('/content/Assignment - Data.csv')

In [ ]:
df

,District,Farmer Name,Model Plot ID,Crop,Varity,Week,Current Crop Stage,Type of Plot,Current Week Activity,Cost of Activity,Labour Used,Cost of Labour,No of Product used,Product used,Product Type,Product name,Qty,Water Used,Cost,Seasonal Challenges
0,Nasrullaganj,Sunil Panwar - Discontinue,MP1,Soyabean,Discontinue,Week 20,0,FP,Harvest of moong,1000,12.0,350.0,NaN,NaN,NaN,NaN,NaN,NaN,5200.0,Normal Rain
1,Nasrullaganj,Sunil Panwar - Discontinue,MP1,Soyabean,Discontinue,Week 20,0,UMP,Harvest of moong,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Normal Rain
2,Nasrullaganj,Narayan Panwar,MP2,Soyabean,Black gold,Week 20,0,FP,No Activity,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Nasrullaganj,Narayan Panwar,MP2,Soyabean,Black gold,Week 20,0,UMP,No Activity,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Nasrullaganj,Rakesh Panwar,MP4,Soyabean,Black gold,Week 20,0,FP,No Activity,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
673,Rehti,Santosh Sahu,MP16,Rice,1718,Week41,113,UMP,Demo,1035,1.0,350.0,NaN,NaN,Insecticide,Azaka Duo + Coragen + Legend,150ml + 30ml + 30gm,60L,NaN,normal weather
674,Rehti,Gourav Gor,MP25,Rice,1886,Week41,113,FP,Spray,1818,1.0,350.0,NaN,NaN,Insecticide,Corteva pexalon + netivo + vajeer,100 ml + 50ml +30ml,60L,NaN,normal weather
675,Rehti,Gourav Gor,MP25,Rice,1886,Week41,113,UMP,No Activity,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,normal weather
676,Rehti,Mohit Nagar,MP23,Rice,Pushpa 1886 and 1718,Week41,113,FP,No Activity,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,normal weather
677,Rehti,Mohit Nagar,MP23,Rice,Pushpa 1886 and 1718,Week41,113,UMP,Demo,1035,1.0,350.0,NaN,NaN,Insecticide,Azaka Duo + Coragen + Legend,150ml + 30ml + 30gm,60L,NaN,normal weather

In [ ]:
df.columns

Index(['District', 'Farmer Name ', 'Model Plot ID', 'Crop', 'Varity', 'Week',
       'Current Crop Stage', 'Type of Plot', 'Current Week Activity',
       'Cost of Activity', 'Labour Used', 'Cost of Labour',
       ' No of Product used ', 'Product used ', 'Product Type',
       'Product name ', 'Qty', 'Water Used', 'Cost', 'Seasonal Challenges'],
      dtype='object')

In [ ]:
df.loc[df['Current Week Activity'] == 'No Activity', 'Labour Used'] = 0

In [ ]:
df

,District,Farmer Name,Model Plot ID,Crop,Varity,Week,Current Crop Stage,Type of Plot,Current Week Activity,Cost of Activity,Labour Used,Cost of Labour,No of Product used,Product used,Product Type,Product name,Qty,Water Used,Cost,Seasonal Challenges
0,Nasrullaganj,Sunil Panwar - Discontinue,MP1,Soyabean,Discontinue,Week 20,0,FP,Harvest of moong,1000,12.0,350.0,NaN,NaN,NaN,NaN,NaN,NaN,5200.0,Normal Rain
1,Nasrullaganj,Sunil Panwar - Discontinue,MP1,Soyabean,Discontinue,Week 20,0,UMP,Harvest of moong,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Normal Rain
2,Nasrullaganj,Narayan Panwar,MP2,Soyabean,Black gold,Week 20,0,FP,No Activity,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Nasrullaganj,Narayan Panwar,MP2,Soyabean,Black gold,Week 20,0,UMP,No Activity,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Nasrullaganj,Rakesh Panwar,MP4,Soyabean,Black gold,Week 20,0,FP,No Activity,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
673,Rehti,Santosh Sahu,MP16,Rice,1718,Week41,113,UMP,Demo,1035,1.0,350.0,NaN,NaN,Insecticide,Azaka Duo + Coragen + Legend,150ml + 30ml + 30gm,60L,NaN,normal weather
674,Rehti,Gourav Gor,MP25,Rice,1886,Week41,113,FP,Spray,1818,1.0,350.0,NaN,NaN,Insecticide,Corteva pexalon + netivo + vajeer,100 ml + 50ml +30ml,60L,NaN,normal weather
675,Rehti,Gourav Gor,MP25,Rice,1886,Week41,113,UMP,No Activity,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,normal weather
676,Rehti,Mohit Nagar,MP23,Rice,Pushpa 1886 and 1718,Week41,113,FP,No Activity,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,normal weather
677,Rehti,Mohit Nagar,MP23,Rice,Pushpa 1886 and 1718,Week41,113,UMP,Demo,1035,1.0,350.0,NaN,NaN,Insecticide,Azaka Duo + Coragen + Legend,150ml + 30ml + 30gm,60L,NaN,normal weather

In [ ]:
      #  'Current Crop Stage', 'Type of Plot', 'Current Week Activity',
      #  'Cost of Activity', 'Labour Used', 'Cost of Labour',
      #  ' No of Product used ', 'Product used ', 'Product Type',
      #  'Product name ', 'Qty', 'Water Used', 'Cost', 'Seasonal Challenges'],
      # dtype='object')

In [ ]:
df.columns

Index(['District', 'Farmer Name ', 'Model Plot ID', 'Crop', 'Varity', 'Week',
       'Current Crop Stage', 'Type of Plot', 'Current Week Activity',
       'Cost of Activity', 'Labour Used', 'Cost of Labour',
       ' No of Product used ', 'Product used ', 'Product Type',
       'Product name ', 'Qty', 'Water Used', 'Cost', 'Seasonal Challenges'],
      dtype='object')

In [ ]:
import pandas as pd
import numpy as np
from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OneHotEncoder
from sklearn.impute import SimpleImputer

# Step 1: Clean the 'Cost of Activity' column to convert it into numeric format
def convert_to_numeric(value):
    try:
        return pd.to_numeric(value, errors='coerce')  # Convert to numeric, invalid parsing returns NaN
    except:
        return np.nan

# Apply the function to 'Cost of Activity' column
df['Cost of Activity'] = df['Cost of Activity'].apply(convert_to_numeric)

# Step 2: Separate rows with and without missing values in 'Cost of Activity'
df_not_missing = df[df['Cost of Activity'].notna()]
df_missing = df[df['Cost of Activity'].isna()]

# Step 3: Extract features and target
features = ['District', 'Crop', 'Varity', 'Week', 'Current Crop Stage', 'Type of Plot', 'Current Week Activity']
target = 'Cost of Activity'

# Step 4: One-hot encode categorical features
encoder = OneHotEncoder(sparse_output=False, handle_unknown='ignore')
X_encoded = encoder.fit_transform(df_not_missing[features])

# Step 5: Impute any missing values in the feature columns
imputer = SimpleImputer(strategy='mean')
X_encoded = imputer.fit_transform(X_encoded)

# Step 6: Train-test split
X_train, X_test, y_train, y_test = train_test_split(X_encoded, df_not_missing[target], test_size=0.2, random_state=42)

# Step 7: Train a Random Forest Regressor
model = RandomForestRegressor(n_estimators=100, random_state=42)
model.fit(X_train, y_train)

# Step 8: Prepare the missing data for prediction
X_missing_encoded = encoder.transform(df_missing[features])
X_missing_encoded = imputer.transform(X_missing_encoded)

# Step 9: Predict the missing values for 'Cost of Activity'
df_missing['Cost of Activity'] = model.predict(X_missing_encoded)

# Step 10: Combine the datasets (rows with predicted and non-missing values)
df_filled = pd.concat([df_not_missing, df_missing])

# Display the resulting DataFrame with the filled values
print(df_filled)

         District                Farmer Name  Model Plot ID      Crop  \
0    Nasrullaganj  Sunil Panwar - Discontinue           MP1  Soyabean
6    Nasrullaganj                Daluram Jaat           MP7  Soyabean
7    Nasrullaganj                Daluram Jaat           MP7  Soyabean
48          Rehti    Nitin Nagar- Discontinue           MP9      Rice
64   Nasrullaganj  Sunil Panwar - Discontinue           MP1  Soyabean
..            ...                         ...           ...       ...
661  Nasrullaganj                Pawan Panwar          MP24  Soyabean
664         Rehti             Sardar Ji Nagar          MP11      Rice
672         Rehti                Santosh Sahu          MP16      Rice
675         Rehti                  Gourav Gor          MP25      Rice
676         Rehti                 Mohit Nagar          MP23      Rice

                   Varity     Week  Current Crop Stage Type of Plot  \
0             Discontinue  Week 20                   0           FP
6              Black gold  Week 20                   0           FP
7              Black gold  Week 20                   0          UMP
48            Discontinue  Week 22                   0           FP
64            Discontinue   Week23                   0           FP
..                    ...      ...                 ...          ...
661            Black gold   Week41                 106          UMP
664                  1886   Week41                 106           FP
672                  1718   Week41                 113           FP
675                  1886   Week41                 113          UMP
676  Pushpa 1886 and 1718   Week41                 113           FP

        Current Week Activity  Cost of Activity  Labour Used  Cost of Labour  \
0            Harvest of moong           1000.00         12.0           350.0
6            Harvest of moong           4000.00          0.0             NaN
7            Harvest of moong           1000.00          0.0             NaN
48                    Harvest           1000.00          NaN             NaN
64   Cultivator and Rotavator           1200.00          NaN             NaN
..                        ...               ...          ...             ...
661               No Activity           1125.98          0.0             NaN
664               No Activity           1124.66          0.0             NaN
672               No Activity           1205.36          0.0             NaN
675               No Activity           1129.52          0.0             NaN
676               No Activity           1240.66          0.0             NaN

      No of Product used   Product used  Product Type Product name   Qty  \
0                     NaN            NaN          NaN           NaN  NaN
6                     NaN            NaN          NaN           NaN  NaN
7                     NaN            NaN          NaN           NaN  NaN
48                    NaN            NaN          NaN           NaN  NaN
64                    NaN            NaN          NaN           NaN  NaN
..                    ...            ...          ...           ...  ...
661                   NaN            NaN          NaN           NaN  NaN
664                   NaN            NaN          NaN           NaN  NaN
672                   NaN            NaN          NaN           NaN  NaN
675                   NaN            NaN          NaN           NaN  NaN
676                   NaN            NaN          NaN           NaN  NaN

    Water Used    Cost Seasonal Challenges
0          NaN  5200.0         Normal Rain
6          NaN  4000.0         Normal Rain
7          NaN  1000.0         Normal Rain
48         NaN  1000.0      Normal Weather
64         NaN  1200.0      Normal Weather
..         ...     ...                 ...
661        NaN     NaN      normal weather
664        NaN     NaN      normal weather
672        NaN     NaN      normal weather
675        NaN     NaN      normal weather
676        NaN     NaN      normal weather

[678 rows x 20 columns]

<ipython-input-123-ea1f41f2da4b>:46: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_missing['Cost of Activity'] = model.predict(X_missing_encoded)

In [ ]:
df_filled['Cost of Activity'] = df_filled['Cost of Activity'].round()

In [ ]:
df_filled

,District,Farmer Name,Model Plot ID,Crop,Varity,Week,Current Crop Stage,Type of Plot,Current Week Activity,Cost of Activity,Labour Used,Cost of Labour,No of Product used,Product used,Product Type,Product name,Qty,Water Used,Cost,Seasonal Challenges
0,Nasrullaganj,Sunil Panwar - Discontinue,MP1,Soyabean,Discontinue,Week 20,0,FP,Harvest of moong,1000.0,12.0,350.0,NaN,NaN,NaN,NaN,NaN,NaN,5200.0,Normal Rain
6,Nasrullaganj,Daluram Jaat,MP7,Soyabean,Black gold,Week 20,0,FP,Harvest of moong,4000.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4000.0,Normal Rain
7,Nasrullaganj,Daluram Jaat,MP7,Soyabean,Black gold,Week 20,0,UMP,Harvest of moong,1000.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1000.0,Normal Rain
48,Rehti,Nitin Nagar- Discontinue,MP9,Rice,Discontinue,Week 22,0,FP,Harvest,1000.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1000.0,Normal Weather
64,Nasrullaganj,Sunil Panwar - Discontinue,MP1,Soyabean,Discontinue,Week23,0,FP,Cultivator and Rotavator,1200.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1200.0,Normal Weather
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
661,Nasrullaganj,Pawan Panwar,MP24,Soyabean,Black gold,Week41,106,UMP,No Activity,1126.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,normal weather
664,Rehti,Sardar Ji Nagar,MP11,Rice,1886,Week41,106,FP,No Activity,1125.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,normal weather
672,Rehti,Santosh Sahu,MP16,Rice,1718,Week41,113,FP,No Activity,1205.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,normal weather
675,Rehti,Gourav Gor,MP25,Rice,1886,Week41,113,UMP,No Activity,1130.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,normal weather
676,Rehti,Mohit Nagar,MP23,Rice,Pushpa 1886 and 1718,Week41,113,FP,No Activity,1241.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,normal weather

In [ ]:
# Step 1: Set 'Labour Used' to 0 where 'Current Week Activity' is 'No Activity'
df_filled.loc[df_filled['Current Week Activity'] == 'No Activity', 'Labour Used'] = 0

# Step 2: Group by 'Current Week Activity' and fill 'Labour Used' with the mode
# First, define a function to fill the mode
def fill_labour_used_with_mode(group):
    # If there's no value in 'Labour Used', find the mode of the non-null values
    if group['Labour Used'].isnull().all():
        return group  # No value to fill, return group as is
    else:
        mode_value = group['Labour Used'].mode()
        if not mode_value.empty:  # Check if mode exists
            group['Labour Used'].fillna(mode_value[0], inplace=True)
    return group

# Step 3: Apply the mode-filling function to each group of 'Current Week Activity'
df_filled = df_filled.groupby('Current Week Activity', group_keys=False).apply(fill_labour_used_with_mode)

# Display the resulting DataFrame

df_filled

<ipython-input-126-039871027b7e>:13: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  group['Labour Used'].fillna(mode_value[0], inplace=True)
<ipython-input-126-039871027b7e>:17: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  df_filled = df_filled.groupby('Current Week Activity', group_keys=False).apply(fill_labour_used_with_mode)

,District,Farmer Name,Model Plot ID,Crop,Varity,Week,Current Crop Stage,Type of Plot,Current Week Activity,Cost of Activity,Labour Used,Cost of Labour,No of Product used,Product used,Product Type,Product name,Qty,Water Used,Cost,Seasonal Challenges
0,Nasrullaganj,Sunil Panwar - Discontinue,MP1,Soyabean,Discontinue,Week 20,0,FP,Harvest of moong,1000.0,12.0,350.0,NaN,NaN,NaN,NaN,NaN,NaN,5200.0,Normal Rain
6,Nasrullaganj,Daluram Jaat,MP7,Soyabean,Black gold,Week 20,0,FP,Harvest of moong,4000.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4000.0,Normal Rain
7,Nasrullaganj,Daluram Jaat,MP7,Soyabean,Black gold,Week 20,0,UMP,Harvest of moong,1000.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1000.0,Normal Rain
48,Rehti,Nitin Nagar- Discontinue,MP9,Rice,Discontinue,Week 22,0,FP,Harvest,1000.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1000.0,Normal Weather
64,Nasrullaganj,Sunil Panwar - Discontinue,MP1,Soyabean,Discontinue,Week23,0,FP,Cultivator and Rotavator,1200.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1200.0,Normal Weather
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
661,Nasrullaganj,Pawan Panwar,MP24,Soyabean,Black gold,Week41,106,UMP,No Activity,1126.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,normal weather
664,Rehti,Sardar Ji Nagar,MP11,Rice,1886,Week41,106,FP,No Activity,1125.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,normal weather
672,Rehti,Santosh Sahu,MP16,Rice,1718,Week41,113,FP,No Activity,1205.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,normal weather
675,Rehti,Gourav Gor,MP25,Rice,1886,Week41,113,UMP,No Activity,1130.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,normal weather
676,Rehti,Mohit Nagar,MP23,Rice,Pushpa 1886 and 1718,Week41,113,FP,No Activity,1241.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,normal weather

In [ ]:
# Step 1: Extract the last 2 characters from the 'Week' column and convert to integer
df_filled['Week'] = df_filled['Week'].str[-2:].astype(int)

# Display the updated DataFrame
df_filled

,District,Farmer Name,Model Plot ID,Crop,Varity,Week,Current Crop Stage,Type of Plot,Current Week Activity,Cost of Activity,Labour Used,Cost of Labour,No of Product used,Product used,Product Type,Product name,Qty,Water Used,Cost,Seasonal Challenges
0,Nasrullaganj,Sunil Panwar - Discontinue,MP1,Soyabean,Discontinue,20,0,FP,Harvest of moong,1000.0,12.0,350.0,NaN,NaN,NaN,NaN,NaN,NaN,5200.0,Normal Rain
6,Nasrullaganj,Daluram Jaat,MP7,Soyabean,Black gold,20,0,FP,Harvest of moong,4000.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4000.0,Normal Rain
7,Nasrullaganj,Daluram Jaat,MP7,Soyabean,Black gold,20,0,UMP,Harvest of moong,1000.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1000.0,Normal Rain
48,Rehti,Nitin Nagar- Discontinue,MP9,Rice,Discontinue,22,0,FP,Harvest,1000.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1000.0,Normal Weather
64,Nasrullaganj,Sunil Panwar - Discontinue,MP1,Soyabean,Discontinue,23,0,FP,Cultivator and Rotavator,1200.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1200.0,Normal Weather
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
661,Nasrullaganj,Pawan Panwar,MP24,Soyabean,Black gold,41,106,UMP,No Activity,1126.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,normal weather
664,Rehti,Sardar Ji Nagar,MP11,Rice,1886,41,106,FP,No Activity,1125.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,normal weather
672,Rehti,Santosh Sahu,MP16,Rice,1718,41,113,FP,No Activity,1205.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,normal weather
675,Rehti,Gourav Gor,MP25,Rice,1886,41,113,UMP,No Activity,1130.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,normal weather
676,Rehti,Mohit Nagar,MP23,Rice,Pushpa 1886 and 1718,41,113,FP,No Activity,1241.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,normal weather

In [ ]:
df_1 = df_filled

In [ ]:
import pandas as pd
import numpy as np
from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OneHotEncoder
from sklearn.impute import SimpleImputer

# Assuming df_filled is already defined and preprocessed as needed

# Step 1: Clean the 'Labour Used' column to ensure it's numeric
df_filled['Labour Used'] = pd.to_numeric(df_filled['Labour Used'], errors='coerce')

# Step 2: Separate rows with and without missing values in 'Labour Used'
df_not_missing_labour = df_filled[df_filled['Labour Used'].notna()]
df_missing_labour = df_filled[df_filled['Labour Used'].isna()]

# Step 3: Extract features and target
features = ['Crop', 'Varity', 'Week', 'Current Crop Stage', 'Type of Plot', 'Current Week Activity', 'Cost of Activity']
target = 'Labour Used'

# Step 4: One-hot encode categorical features
encoder = OneHotEncoder(sparse_output=False, handle_unknown='ignore')
X_encoded = encoder.fit_transform(df_not_missing_labour[features])

# Step 5: Impute any missing values in the feature columns
imputer = SimpleImputer(strategy='mean')
X_encoded = imputer.fit_transform(X_encoded)

# Step 6: Train-test split
X_train, X_test, y_train, y_test = train_test_split(X_encoded, df_not_missing_labour[target], test_size=0.2, random_state=42)

# Step 7: Train a Random Forest Regressor
model = RandomForestRegressor(n_estimators=100, random_state=42)
model.fit(X_train, y_train)

# Step 8: Prepare the missing data for prediction
X_missing_encoded = encoder.transform(df_missing_labour[features])
X_missing_encoded = imputer.transform(X_missing_encoded)

# Step 9: Predict the missing values for 'Labour Used'
df_missing_labour['Labour Used'] = model.predict(X_missing_encoded)

# Step 10: Combine the datasets (rows with predicted and non-missing values)
df_filled_final = pd.concat([df_not_missing_labour, df_missing_labour])

# Step 11: Convert 'Labour Used' to integer
df_filled_final['Labour Used'] = df_filled_final['Labour Used'].round().astype(int)

# Display the resulting DataFrame with the filled values
print(df_filled_final)

         District                Farmer Name  Model Plot ID      Crop  \
0    Nasrullaganj  Sunil Panwar - Discontinue           MP1  Soyabean
6    Nasrullaganj                Daluram Jaat           MP7  Soyabean
7    Nasrullaganj                Daluram Jaat           MP7  Soyabean
183         Rehti               Srishir Dubay          MP10      Rice
214         Rehti               Srishir Dubay          MP10      Rice
..            ...                         ...           ...       ...
625  Nasrullaganj                 Vinod Patel          MP20  Soyabean
626  Nasrullaganj                Vivek Panwar          MP21  Soyabean
627  Nasrullaganj                Vivek Panwar          MP21  Soyabean
628  Nasrullaganj                Pawan Panwar          MP24  Soyabean
629  Nasrullaganj                Pawan Panwar          MP24  Soyabean

          Varity  Week  Current Crop Stage Type of Plot Current Week Activity  \
0    Discontinue    20                   0           FP      Harvest of moong
6     Black gold    20                   0           FP      Harvest of moong
7     Black gold    20                   0          UMP      Harvest of moong
183    Kranti LG    26                   8          UMP           No Activity
214    Kranti LG    27                  15           FP            Irrigation
..           ...   ...                 ...          ...                   ...
625   Black gold    40                  99          UMP               Harvest
626   Black gold    40                  99           FP               Harvest
627   Black gold    40                  99          UMP               Harvest
628   Black gold    40                  99           FP               Harvest
629   Black gold    40                  99          UMP               Harvest

     Cost of Activity  Labour Used  Cost of Labour   No of Product used   \
0              1000.0           12           350.0                   NaN
6              4000.0            0             NaN                   NaN
7              1000.0            0             NaN                   NaN
183             260.0            0             NaN                   NaN
214             500.0            1             NaN                   NaN
..                ...          ...             ...                   ...
625            1015.0            1             NaN                   NaN
626             809.0            1             NaN                   NaN
627            1015.0            1             NaN                   NaN
628             809.0            1             NaN                   NaN
629            1015.0            1             NaN                   NaN

     Product used  Product Type Product name    Qty Water Used    Cost  \
0              NaN          NaN           NaN   NaN        NaN  5200.0
6              NaN          NaN           NaN   NaN        NaN  4000.0
7              NaN          NaN           NaN   NaN        NaN  1000.0
183            NaN   Fertilizer           DAP  10KG        NaN   260.0
214            NaN          NaN           NaN   NaN        NaN   500.0
..             ...          ...           ...   ...        ...     ...
625            NaN          NaN           NaN   NaN        NaN     NaN
626            NaN          NaN           NaN   NaN        NaN     NaN
627            NaN          NaN           NaN   NaN        NaN     NaN
628            NaN          NaN           NaN   NaN        NaN     NaN
629            NaN          NaN           NaN   NaN        NaN     NaN

    Seasonal Challenges
0           Normal Rain
6           Normal Rain
7           Normal Rain
183         Normal Rain
214       Moderate Rain
..                  ...
625      normal weather
626      normal weather
627      normal weather
628      normal weather
629      normal weather

[678 rows x 20 columns]

<ipython-input-129-4553f3852272>:41: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_missing_labour['Labour Used'] = model.predict(X_missing_encoded)

In [ ]:
df_1 = df_filled_final

In [ ]:
df_1

,District,Farmer Name,Model Plot ID,Crop,Varity,Week,Current Crop Stage,Type of Plot,Current Week Activity,Cost of Activity,Labour Used,Cost of Labour,No of Product used,Product used,Product Type,Product name,Qty,Water Used,Cost,Seasonal Challenges
0,Nasrullaganj,Sunil Panwar - Discontinue,MP1,Soyabean,Discontinue,20,0,FP,Harvest of moong,1000.0,12,350.0,NaN,NaN,NaN,NaN,NaN,NaN,5200.0,Normal Rain
6,Nasrullaganj,Daluram Jaat,MP7,Soyabean,Black gold,20,0,FP,Harvest of moong,4000.0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4000.0,Normal Rain
7,Nasrullaganj,Daluram Jaat,MP7,Soyabean,Black gold,20,0,UMP,Harvest of moong,1000.0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1000.0,Normal Rain
183,Rehti,Srishir Dubay,MP10,Rice,Kranti LG,26,8,UMP,No Activity,260.0,0,NaN,NaN,NaN,Fertilizer,DAP,10KG,NaN,260.0,Normal Rain
214,Rehti,Srishir Dubay,MP10,Rice,Kranti LG,27,15,FP,Irrigation,500.0,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,500.0,Moderate Rain
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
625,Nasrullaganj,Vinod Patel,MP20,Soyabean,Black gold,40,99,UMP,Harvest,1015.0,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,normal weather
626,Nasrullaganj,Vivek Panwar,MP21,Soyabean,Black gold,40,99,FP,Harvest,809.0,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,normal weather
627,Nasrullaganj,Vivek Panwar,MP21,Soyabean,Black gold,40,99,UMP,Harvest,1015.0,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,normal weather
628,Nasrullaganj,Pawan Panwar,MP24,Soyabean,Black gold,40,99,FP,Harvest,809.0,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,normal weather
629,Nasrullaganj,Pawan Panwar,MP24,Soyabean,Black gold,40,99,UMP,Harvest,1015.0,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,normal weather

In [ ]:
df_filled.loc[df_filled['Current Week Activity'] == 'No Activity', 'Labour Used'] = 0

In [ ]:
df_1.loc[df_1['Current Week Activity'] == 'No Activity', 'Labour Used'] = 0

In [ ]:
df_1

,District,Farmer Name,Model Plot ID,Crop,Varity,Week,Current Crop Stage,Type of Plot,Current Week Activity,Cost of Activity,Labour Used,Cost of Labour,No of Product used,Product used,Product Type,Product name,Qty,Water Used,Cost,Seasonal Challenges
0,Nasrullaganj,Sunil Panwar - Discontinue,MP1,Soyabean,Discontinue,Week 20,0,FP,Harvest of moong,1000.00,12.0,350.0,NaN,NaN,NaN,NaN,NaN,NaN,5200.0,Normal Rain
6,Nasrullaganj,Daluram Jaat,MP7,Soyabean,Black gold,Week 20,0,FP,Harvest of moong,4000.00,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4000.0,Normal Rain
7,Nasrullaganj,Daluram Jaat,MP7,Soyabean,Black gold,Week 20,0,UMP,Harvest of moong,1000.00,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1000.0,Normal Rain
48,Rehti,Nitin Nagar- Discontinue,MP9,Rice,Discontinue,Week 22,0,FP,Harvest,1000.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1000.0,Normal Weather
64,Nasrullaganj,Sunil Panwar - Discontinue,MP1,Soyabean,Discontinue,Week23,0,FP,Cultivator and Rotavator,1200.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1200.0,Normal Weather
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
661,Nasrullaganj,Pawan Panwar,MP24,Soyabean,Black gold,Week41,106,UMP,No Activity,1125.98,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,normal weather
664,Rehti,Sardar Ji Nagar,MP11,Rice,1886,Week41,106,FP,No Activity,1124.66,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,normal weather
672,Rehti,Santosh Sahu,MP16,Rice,1718,Week41,113,FP,No Activity,1205.36,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,normal weather
675,Rehti,Gourav Gor,MP25,Rice,1886,Week41,113,UMP,No Activity,1129.52,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,normal weather
676,Rehti,Mohit Nagar,MP23,Rice,Pushpa 1886 and 1718,Week41,113,FP,No Activity,1240.66,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,normal weather

In [ ]:
df_1[df_1['Current Week Activity']=="No Activity"]

,District,Farmer Name,Model Plot ID,Crop,Varity,Week,Current Crop Stage,Type of Plot,Current Week Activity,Cost of Activity,Labour Used,Cost of Labour,No of Product used,Product used,Product Type,Product name,Qty,Water Used,Cost,Seasonal Challenges
183,Rehti,Srishir Dubay,MP10,Rice,Kranti LG,Week26,8,UMP,No Activity,260.000000,0.0,NaN,NaN,NaN,Fertilizer,DAP,10KG,NaN,260.0,Normal Rain
540,Rehti,Manoj Kevat,MP13,Rice,Pushpa P1,Week37,92,FP,No Activity,877.000000,0.0,350.0,NaN,NaN,Insecticide + fungicide,Coromandel Astra + Coromandel Magnite + tata g...,60gm + 105ml + 50ml + 35ml,60L,NaN,moderate Rain
542,Rehti,Manoj Nagar,MP15,Rice,Pushpa P1,Week37,85,FP,No Activity,535.000000,0.0,350.0,NaN,NaN,Insecticide + Insecticide + (Phenmetrazine) +...,Banjosuper + \nParijat + \nCLSL + \nParijat +...,25 ml + 125gm + 80gm + 150ml + 50ml +60ml,80L,NaN,moderate Rain
2,Nasrullaganj,Narayan Panwar,MP2,Soyabean,Black gold,Week 20,0,FP,No Activity,1749.820000,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Nasrullaganj,Narayan Panwar,MP2,Soyabean,Black gold,Week 20,0,UMP,No Activity,1285.956667,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
661,Nasrullaganj,Pawan Panwar,MP24,Soyabean,Black gold,Week41,106,UMP,No Activity,1125.980000,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,normal weather
664,Rehti,Sardar Ji Nagar,MP11,Rice,1886,Week41,106,FP,No Activity,1124.660000,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,normal weather
672,Rehti,Santosh Sahu,MP16,Rice,1718,Week41,113,FP,No Activity,1205.360000,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,normal weather
675,Rehti,Gourav Gor,MP25,Rice,1886,Week41,113,UMP,No Activity,1129.520000,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,normal weather
676,Rehti,Mohit Nagar,MP23,Rice,Pushpa 1886 and 1718,Week41,113,FP,No Activity,1240.660000,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,normal weather

In [ ]:
df_1['Labour Used'].value_counts()

Labour Used
0.0     356
1.0      34
0.5       6
8.0       2
12.0      1
2.0       1
3.0       1
Name: count, dtype: int64

In [ ]:
df_1['Labour Used'].isnull().sum()

277

In [ ]:
df_2 = df_1

In [ ]:
df_1['Labour Used'].isnull().sum()

0

In [ ]:
# 631 values which were missing in labour used initiallly
# 354 rows in which No Activity was written in Current Activity
# Out of these 631 values we filled 354 with 0.as_integer_ratio
# We were left with 277 empty rows

In [ ]:
df_1[df_1['Current Week Activity'] == "No Activity"]

,District,Farmer Name,Model Plot ID,Crop,Varity,Week,Current Crop Stage,Type of Plot,Current Week Activity,Cost of Activity,Labour Used,Cost of Labour,No of Product used,Product used,Product Type,Product name,Qty,Water Used,Cost,Seasonal Challenges
183,Rehti,Srishir Dubay,MP10,Rice,Kranti LG,Week26,8,UMP,No Activity,260.000000,0.0,NaN,NaN,NaN,Fertilizer,DAP,10KG,NaN,260.0,Normal Rain
540,Rehti,Manoj Kevat,MP13,Rice,Pushpa P1,Week37,92,FP,No Activity,877.000000,0.0,350.0,NaN,NaN,Insecticide + fungicide,Coromandel Astra + Coromandel Magnite + tata g...,60gm + 105ml + 50ml + 35ml,60L,NaN,moderate Rain
542,Rehti,Manoj Nagar,MP15,Rice,Pushpa P1,Week37,85,FP,No Activity,535.000000,0.0,350.0,NaN,NaN,Insecticide + Insecticide + (Phenmetrazine) +...,Banjosuper + \nParijat + \nCLSL + \nParijat +...,25 ml + 125gm + 80gm + 150ml + 50ml +60ml,80L,NaN,moderate Rain
2,Nasrullaganj,Narayan Panwar,MP2,Soyabean,Black gold,Week 20,0,FP,No Activity,1749.820000,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Nasrullaganj,Narayan Panwar,MP2,Soyabean,Black gold,Week 20,0,UMP,No Activity,1285.956667,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
661,Nasrullaganj,Pawan Panwar,MP24,Soyabean,Black gold,Week41,106,UMP,No Activity,1125.980000,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,normal weather
664,Rehti,Sardar Ji Nagar,MP11,Rice,1886,Week41,106,FP,No Activity,1124.660000,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,normal weather
672,Rehti,Santosh Sahu,MP16,Rice,1718,Week41,113,FP,No Activity,1205.360000,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,normal weather
675,Rehti,Gourav Gor,MP25,Rice,1886,Week41,113,UMP,No Activity,1129.520000,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,normal weather
676,Rehti,Mohit Nagar,MP23,Rice,Pushpa 1886 and 1718,Week41,113,FP,No Activity,1240.660000,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,normal weather

In [ ]:
df_1.loc[df_1['Current Week Activity'] == "No Activity", 'Cost of Labour'] = 0

In [ ]:
# Step 1: Clean the 'Cost of Labour' column to ensure it's numeric
df_1['Cost of Labour'] = pd.to_numeric(df_1['Cost of Labour'], errors='coerce')

# Step 2: Separate rows with and without missing values in 'Cost of Labour'
df_not_missing_labour = df_1[df_1['Cost of Labour'].notna()]
df_missing_labour = df_1[df_1['Cost of Labour'].isna()]

# Step 3: Define the features and target variable
features = ['Crop', 'Varity', 'Week', 'Current Crop Stage', 'Current Week Activity']
target = 'Cost of Labour'

# Step 4: One-hot encode categorical features
encoder = OneHotEncoder(sparse_output=False, handle_unknown='ignore')
X_encoded = encoder.fit_transform(df_not_missing_labour[features])

# Step 5: Impute any missing values in the feature columns
imputer = SimpleImputer(strategy='mean')
X_encoded = imputer.fit_transform(X_encoded)

# Step 6: Train-test split
X_train, X_test, y_train, y_test = train_test_split(X_encoded, df_not_missing_labour[target], test_size=0.2, random_state=42)

# Step 7: Train a Random Forest Regressor
model = RandomForestRegressor(n_estimators=100, random_state=42)
model.fit(X_train, y_train)

# Step 8: Prepare the missing data for prediction
X_missing_encoded = encoder.transform(df_missing_labour[features])
X_missing_encoded = imputer.transform(X_missing_encoded)

# Step 9: Predict the missing values for 'Cost of Labour'
predicted_cost_labour = model.predict(X_missing_encoded)

# Step 10: Fill in the missing 'Cost of Labour' values in df_1
df_1.loc[df_1['Cost of Labour'].isna(), 'Cost of Labour'] = np.round(predicted_cost_labour).astype(int)

# Display the resulting DataFrame with the filled values
df_1

,District,Farmer Name,Model Plot ID,Crop,Varity,Week,Current Crop Stage,Type of Plot,Current Week Activity,Cost of Activity,Labour Used,Cost of Labour,No of Product used,Product used,Product Type,Product name,Qty,Water Used,Cost,Seasonal Challenges
0,Nasrullaganj,Sunil Panwar - Discontinue,MP1,Soyabean,Discontinue,20,0,FP,Harvest of moong,1000.0,12,350.0,NaN,NaN,NaN,NaN,NaN,NaN,5200.0,Normal Rain
6,Nasrullaganj,Daluram Jaat,MP7,Soyabean,Black gold,20,0,FP,Harvest of moong,4000.0,0,350.0,NaN,NaN,NaN,NaN,NaN,NaN,4000.0,Normal Rain
7,Nasrullaganj,Daluram Jaat,MP7,Soyabean,Black gold,20,0,UMP,Harvest of moong,1000.0,0,350.0,NaN,NaN,NaN,NaN,NaN,NaN,1000.0,Normal Rain
183,Rehti,Srishir Dubay,MP10,Rice,Kranti LG,26,8,UMP,No Activity,260.0,0,0.0,NaN,NaN,Fertilizer,DAP,10KG,NaN,260.0,Normal Rain
214,Rehti,Srishir Dubay,MP10,Rice,Kranti LG,27,15,FP,Irrigation,500.0,1,338.0,NaN,NaN,NaN,NaN,NaN,NaN,500.0,Moderate Rain
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
625,Nasrullaganj,Vinod Patel,MP20,Soyabean,Black gold,40,99,UMP,Harvest,1015.0,1,332.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,normal weather
626,Nasrullaganj,Vivek Panwar,MP21,Soyabean,Black gold,40,99,FP,Harvest,809.0,1,332.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,normal weather
627,Nasrullaganj,Vivek Panwar,MP21,Soyabean,Black gold,40,99,UMP,Harvest,1015.0,1,332.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,normal weather
628,Nasrullaganj,Pawan Panwar,MP24,Soyabean,Black gold,40,99,FP,Harvest,809.0,1,332.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,normal weather
629,Nasrullaganj,Pawan Panwar,MP24,Soyabean,Black gold,40,99,UMP,Harvest,1015.0,1,332.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,normal weather

In [ ]:
df_filled['Cost of Labour'].value_counts()

Cost of Labour
350.0     39
200.0      9
500.0      2
625.0      2
400.0      2
700.0      2
1000.0     1
Name: count, dtype: int64

In [ ]:
df_1['Cost of Labour'].value_counts()

Cost of Labour
0.0      354
350.0    125
332.0     41
342.0     25
212.0     23
360.0     17
338.0     10
200.0      9
351.0      9
329.0      7
366.0      6
372.0      4
368.0      4
327.0      4
354.0      4
204.0      3
321.0      3
324.0      3
347.0      2
358.0      2
373.0      2
361.0      2
400.0      2
700.0      2
357.0      2
625.0      2
500.0      2
320.0      1
328.0      1
334.0      1
455.0      1
344.0      1
343.0      1
356.0      1
333.0      1
573.0      1
Name: count, dtype: int64

In [ ]:
df_2['Cost of Labour'].isnull().sum()

0

In [ ]:
df_1

,District,Farmer Name,Model Plot ID,Crop,Varity,Week,Current Crop Stage,Type of Plot,Current Week Activity,Cost of Activity,Labour Used,Cost of Labour,No of Product used,Product used,Product Type,Product name,Qty,Water Used,Cost,Seasonal Challenges
0,Nasrullaganj,Sunil Panwar - Discontinue,MP1,Soyabean,Discontinue,20,0,FP,Harvest of moong,1000.0,12,350.0,NaN,NaN,NaN,NaN,NaN,NaN,5200.0,Normal Rain
6,Nasrullaganj,Daluram Jaat,MP7,Soyabean,Black gold,20,0,FP,Harvest of moong,4000.0,0,350.0,NaN,NaN,NaN,NaN,NaN,NaN,4000.0,Normal Rain
7,Nasrullaganj,Daluram Jaat,MP7,Soyabean,Black gold,20,0,UMP,Harvest of moong,1000.0,0,350.0,NaN,NaN,NaN,NaN,NaN,NaN,1000.0,Normal Rain
183,Rehti,Srishir Dubay,MP10,Rice,Kranti LG,26,8,UMP,No Activity,260.0,0,0.0,NaN,NaN,Fertilizer,DAP,10KG,NaN,260.0,Normal Rain
214,Rehti,Srishir Dubay,MP10,Rice,Kranti LG,27,15,FP,Irrigation,500.0,1,338.0,NaN,NaN,NaN,NaN,NaN,NaN,500.0,Moderate Rain
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
625,Nasrullaganj,Vinod Patel,MP20,Soyabean,Black gold,40,99,UMP,Harvest,1015.0,1,332.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,normal weather
626,Nasrullaganj,Vivek Panwar,MP21,Soyabean,Black gold,40,99,FP,Harvest,809.0,1,332.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,normal weather
627,Nasrullaganj,Vivek Panwar,MP21,Soyabean,Black gold,40,99,UMP,Harvest,1015.0,1,332.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,normal weather
628,Nasrullaganj,Pawan Panwar,MP24,Soyabean,Black gold,40,99,FP,Harvest,809.0,1,332.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,normal weather
629,Nasrullaganj,Pawan Panwar,MP24,Soyabean,Black gold,40,99,UMP,Harvest,1015.0,1,332.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,normal weather

In [ ]:
df_1.to_csv('final_data.csv', index=False)